### ISSUE TITLE
Cosmic-screenshot panick

### ISSUE THREAD

**Issue by wesbluemarine** [ublue-os/cosmic#36]
Screenshot tool does not work on cosmic-base (looks like the same issue of cosmic-greeter).

```
makaba@fedora:~$ sudo setenforce 0 && getenforce
setenforce: SELinux is disabled
makaba@fedora:~$ cosmic-screenshot --interactive=false --modal=false
thread 'main' panicked at src/main.rs:69:10:
failed to send screenshot request: Zbus(MethodError(OwnedErrorName(ErrorName(Str(Owned("org.freedesktop.DBus.Error.UnknownMethod")))), Some("No such interface “org.freedesktop.portal.Screenshot” on object at path /org/freedesktop/portal/desktop"), Msg { type: Error, sender: UniqueName(Str(Borrowed(":1.26"))), reply-serial: 17, body: Signature("s") }))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
makaba@fedora:~$ cosmic-screenshot
thread 'main' panicked at src/main.rs:69:10:
failed to send screenshot request: Zbus(MethodError(OwnedErrorName(ErrorName(Str(Owned("org.freedesktop.DBus.Error.UnknownMethod")))), Some("No such interface “org.freedesktop.portal.Screenshot” on object at path /org/freedesktop/portal/desktop"), Msg { type: Error, sender: UniqueName(Str(Borrowed(":1.26"))), reply-serial: 17, body: Signature("s") }))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
makaba@fedora:~$

```

**Comment by idnovic** [comment]
It works for me with a newer build.

**Comment by nevdelap** [comment]
I have this with the latest installed this evening.

I have this. It was working but I removed and reinstalled cosmic, on Arch, by removing cosmic-session-git and its dependencies and reinstalling it.

```
23:27:48 zen ~ cosmic-screenshot
thread 'main' panicked at src/main.rs:69:10:
failed to send screenshot request: Zbus(MethodError(OwnedErrorName(ErrorName(Str(Owned("org.freedesktop.DBus.Error.UnknownMethod")))), Some("No such interface “org.freedesktop.portal.Screenshot” on object at path /org/freedesktop/portal/desktop"), Msg { type: Error, sender: UniqueName(Str(Borrowed(":1.11"))), reply-serial: 17, body: Signature("s") }))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
23:27:56 zen ~ 101
```

**Comment by ryanabx** [comment]
> I have this with the latest installed this evening.
> 
> I have this. It was working but I removed and reinstalled cosmic, on Arch, by removing cosmic-session-git and its dependencies and reinstalling it.
> 
> ```
> 23:27:48 zen ~ cosmic-screenshot
> thread 'main' panicked at src/main.rs:69:10:
> failed to send screenshot request: Zbus(MethodError(OwnedErrorName(ErrorName(Str(Owned("org.freedesktop.DBus.Error.UnknownMethod")))), Some("No such interface “org.freedesktop.portal.Screenshot” on object at path /org/freedesktop/portal/desktop"), Msg { type: Error, sender: UniqueName(Str(Borrowed(":1.11"))), reply-serial: 17, body: Signature("s") }))
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> 23:27:56 zen ~ 101
> ```

This is an issue tracker for Fedora, not arch, but I'll try to help here.

The error is telling you there's no screenshot portal available, try installing xdg-desktop-portal-cosmic or the fallback xdg-desktop-portal-gtk

**Comment by nevdelap** [comment]
Thanks @ryanabx. `xdg-desktop-portal-cosmic` was already installed and with `xdg-desktop-portal-gtk` installed it does the same. There's also pop-os/cosmic-epoch#887, hopefully when a solution is found in one it will be the solution in the other too. Thanks again. 👍
