### ISSUE TITLE
cosmic-silverblue image does fails to start

### ISSUE THREAD

**Issue by erik-balfe** [ublue-os/cosmic#48]
I just installed fedora silverblue 40, then ran the first command in the readme here to rebase to the cosmic-silverblue image.
I get this error on boot:

```log
2024-07-26T22:54:08.288042Z ERROR cosmic_comp::config: Failed to read config 'workspaces': NoConfigDirectory
2024-07-26T22:54:08.288136Z ERROR cosmic_settings_config: Failed to read local shortcuts config "system_actions": NoConfigDirectory
2024-07-26T22:54:08.288213Z WARN cosmic_settings_config::shortcuts::ram: Key-binding {"Comma"} only matched case insensitive for "comma"
2024-07-26T22:54:08.288229Z WARN cosmic_settings_config::shortcuts::ram: Key-binding {"Comma"} only matched case insensitive for "comma"
2024-07-26T22:54:08.288245Z WARN cosmic_settings_config::shortcuts::ram: Key-binding {"Period"} only matched case insensitive for "period"
2024-07-26T22:54:08.288260Z WARN cosmic_settings_config::shortcuts::ram: Key-binding {"Comma"} only matched case insensitive for "comma"
2024-07-26T22:54:08.288275Z ERROR cosmic_settings_config::shortcuts: Failed to become owner of name "org.cosmic.ConfigDaemon": Unable to acquire bus name: { "name": "org.cosmic.ConfigDaemon", "error": NotFound, message: "No such file or directory" }}
2024-07-26T22:54:08.380925Z WARN [libgbm|backend/egl/context]: Ignoring requested context priority, EGL_IMG_context_priority not supported priority=High
2024-07-26T22:54:08.380973Z WARN [libgbm|backend/egl/context]: Ignoring requested context priority, EGL_IMG_context_priority not supported priority=High
2024-07-26T22:54:08.384149Z WARN [libgbm|backend/egl/context]: Ignoring requested context priority, EGL_IMG_context_priority not supported priority=High
2024-07-26T22:54:08.397825Z WARN [libgbm|backend/egl/context]: Ignoring requested context priority, EGL_IMG_context_priority not supported priority=High
2024-07-26T22:54:08.415073Z WARN cosmic_comp::wayland::compositor: Preferred format ARGB not available: NoSupportedPixelFormat
2024-07-26T22:54:08.415132Z WARN cosmic_comp::wayland::compositor: Preferred format ARGB not available: NoSupportedPixelFormat
2024-07-26T22:54:08.529562Z ERROR panic: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error::NoDevices(DrNode { dev: 57984, ty: Render })': src/backend/kms/surface/mod.rs:313
0: <unknown>
1: <unknown>
2: <unknown>
3: <unknown>
4: <unknown>
5: <unknown>
6: <unknown>
7: <unknown>
8: <unknown>
9: <unknown>
10: <unknown>
11: <unknown>
12: <unknown>
13: <unknown>
14: <unknown>
15: __libc_start_call_main
16: __libc_start_main_impl
17: <unknown>

2024-07-26T22:54:08.529552Z ERROR panic: thread 'surface-Virtual-1' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }': /buildir/build/BUILD/cosmic-comp-f44e46fa4493dcacbf656a6cfeb5dbe7dced55c5/vendor/smithay/src/desktop/space/mod.rs:69
0: <unknown>
1: <unknown>
2: <unknown>
3: <unknown>
4: <unknown>
5: <unknown>
6: <unknown>
7: <unknown>
8: <unknown>
9: <unknown>
10: <unknown>
11: <unknown>
12: <unknown>
13: <unknown>
14: <unknown>
15: <unknown>
16: start_thread
17: __clone3
```

Anyone faced this before? Is there a way for me to install it and run?

**Comment by erik-balfe** [comment]
I opened issue on Cosmic repo https://github.com/pop-os/cosmic-epoch/issues/456

**Comment by ryanabx** [comment]
I think it's just a config parsing error, might need to reset your configs

**Comment by 616b2f** [comment]
the issue is that the user "cosmic-greeter" and "greetd" is not in "/etc/passwd" file, also the corresponding groups where not populated, at least it was the issue for me:

This is how I resolved it:

```bash
$ grep -E '^greetd:' /usr/etc/passwd | sudo tee -a /etc/passwd
$ grep -E '^cosmic-greeter:' /usr/etc/passwd | sudo tee -a /etc/passwd
$ grep -E '^greetd:' /usr/etc/group | sudo tee -a /etc/group
$ grep -E '^cosmic-greeter:' /usr/etc/group | sudo tee -a /etc/group
```

I hope it helps

**Comment by m2Giles** [comment]
Did you rebase from another image?

**Comment by 616b2f** [comment]
> Did you rebase from another image?

yes, from silverblue

> I see. Yeah, same as swapping from kde to gnome or back and forth. You also will need to add to /etc/shadow as well.

This was not necessary, at least for me.

**Comment by Drakulix** [comment]
This sounds like a mistake on this image or the greetd package. These shouldn't be in `/usr/etc/passwd` and so on (only populating correctly if these don't exist from a previous image), but handled via `systemd-sysusers`, so the user would get created correctly and automatically, when rebasing.

**Comment by m2Giles** [comment]
> This sounds like a mistake on this image or the greetd package. These shouldn't be in `/usr/etc/passwd` and so on (only populating correctly if these don't exist from a previous image), but handled via `systemd-sysusers`, so the user would get created correctly and automatically, when rebasing.

I just was able to rebase without a problem to my cosmic image and didn't have to modify /etc/passwd. There was some issue on the VM I tried but worked fine on hardware 

Greetd was extremely verbose on the console while using console on hardware.

**Comment by erik-balfe** [comment]
> the issue is that the user "cosmic-greeter" and "greetd" is not in "/etc/passwd" file, also the corresponding groups where not populated, at least it was the issue for me:
> 
> This is how I resolved it:
> 
> ```shell
> $ grep -E '^greetd:' /usr/etc/passwd | sudo tee -a /etc/passwd
> $ grep -E '^cosmic-greeter:' /usr/etc/passwd | sudo tee -a /etc/passwd
> $ grep -E '^greetd:' /usr/etc/group | sudo tee -a /etc/group
> $ grep -E '^cosmic-greeter:' /usr/etc/group | sudo tee -a /etc/group
> ```
> 
> I hope it helps

That helped me. Thanks a lot! Right after that i tried to start cosmic-greeter service again and got this error:

![error_screenshot](https://github.com/user-attachments/assets/6f3dbc45-cf39-4eee-93a6-5b84b96996ee)

But after restart it was ok. I then managed to login to the system and finally try cosmic desktop!
